### PR TITLE
Handle different Etherscan getsource API responses

### PR DESCRIPTION
**Pull request by naddison36**
Bumped dependencies

### CODE REVIEW

**Comment by ubaistp** [comment]
Hi

**Comment by jgallegos91** [comment]
Hello

**Comment by jgallegos91** [comment]
I don’t know what I do half the time but tbh that’s how I learn how things work is seeing the results

**Comment by jgallegos91** [comment]
I know that sounds very immature but that not how I fully understand things and I just started using hit and it seems to be exactly what I need to brush up on if I make a mistake or you know rice I did something please don’t hesitate to correct me. I would very much appreciate it

**Pull request merged**
