### PR TITLE
Parse contracts on Etherscan with multiple Solidity files

### PR DESCRIPTION
**Pull request by naddison36**
An example is Aave's LendingPool  contract https://etherscan.io/address/0xc6845a5c768bf8d7681249f8927877efda425baf#code

### CODE REVIEW

**Review by Scheusal13 — COMMENTED** [review]
0xEa5C920973eBfff95270dd52c8045c4e6eBFc847

**Review by Scheusal13 — COMMENTED** [review]
0xEa5C920973eBfff95270dd52c8045c4e6eBFc847

**Review by Ikaberry202 — COMMENTED** [review]
Good to go

**Comment by ToTheHighestTopMoon** [comment]
What’s good where can we have a meeting with my team

**Review by BigBlueHundids — COMMENTED** [review]
>.

**Pull request merged**
